"""增加commit，有助于理解字段含义

Revision ID: 54ecad89d8f8
Revises: 61ecc2a0d299
Create Date: 2026-02-16 03:24:15.686990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ecad89d8f8'
down_revision: Union[str, Sequence[str], None] = '61ecc2a0d299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               comment='自增主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=64),
               comment='学号，唯一标识符',
               existing_nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='学生姓名',
               existing_nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='性别，取值范围：男, 女, 其他',
               existing_nullable=True)
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.DATE(),
               comment='出生日期',
               existing_nullable=False)
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               comment='入学日期',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('students', 'major',
               existing_type=sa.VARCHAR(length=100),
               comment='所属专业名称',
               existing_nullable=False)
    op.alter_column('students', 'class_name',
               existing_type=sa.VARCHAR(length=50),
               comment='行政班级名称，例如：计算机2401班',
               existing_nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='电子邮箱地址',
               existing_nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系电话/手机号',
               existing_nullable=True)
    op.alter_column('students', 'address',
               existing_type=sa.TEXT(),
               comment='家庭或通讯详细地址',
               existing_nullable=True)
    op.alter_column('students', 'gpa',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='平均学分绩点（GPA），范围0.00-4.00',
               existing_nullable=True)
    op.alter_column('students', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='学籍状态：active(在读), inactive(休学/离校), graduated(毕业)',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='学籍状态：active(在读), inactive(休学/离校), graduated(毕业)',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('students', 'gpa',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='平均学分绩点（GPA），范围0.00-4.00',
               existing_nullable=True)
    op.alter_column('students', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='家庭或通讯详细地址',
               existing_nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='联系电话/手机号',
               existing_nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='电子邮箱地址',
               existing_nullable=True)
    op.alter_column('students', 'class_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='行政班级名称，例如：计算机2401班',
               existing_nullable=False)
    op.alter_column('students', 'major',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='所属专业名称',
               existing_nullable=False)
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='入学日期',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='出生日期',
               existing_nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='性别，取值范围：男, 女, 其他',
               existing_nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学生姓名',
               existing_nullable=False)
    op.alter_column('students', 'student_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='学号，唯一标识符',
               existing_nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自增主键ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
