"""change students table

Revision ID: 9ef966fd378e
Revises: 54ecad89d8f8
Create Date: 2026-02-17 08:05:35.310813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef966fd378e'
down_revision: Union[str, Sequence[str], None] = '54ecad89d8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='性别，取值范围：male, female, other',
               existing_comment='性别，取值范围：男, 女, 其他',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='性别，取值范围：男, 女, 其他',
               existing_comment='性别，取值范围：male, female, other',
               existing_nullable=True)
    # ### end Alembic commands ###
